version: 2.1

jobs:
  build-and-test:  
    description: Setup and run application tests
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      # Checkout the code.
      - checkout
      # Firstly, compile the project
      - run: dotnet build
      # Run all unit tests in the solution
      - run:
          name: Run all unit tests in the solution
          command: |
            dotnet test --no-build --logger "trx"
      # Populate test results
      - run:
          name: test results
          when: always
          command: |
              dotnet tool install -g trx2junit
              export PATH="$PATH:/root/.dotnet/tools"
              trx2junit tests/**/TestResults/*.trx
      - store_test_results:
          path: tests/TestResults
      - store_artifacts:
          path: tests/TestResults
          destination: TestResults

workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  sample: 
    jobs:
      - build-and-test
