version: 2.1

orbs:
  vulnerability-checker: whitesource/vulnerability-checker@19.10.1

jobs:
  run-backend-unit-tests:  
    description: Setup and run backend unit tests
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      # Checkout the code.
      - checkout
      # Run all unit tests in the solution
      - run:
          name: Run all unit tests in the backend application
          command: |
            dotnet test --logger "trx" 
      # Populate test results
      - run:
          name: Convert test results to junit xml format
          when: always
          command: |
              mkdir Tests/TestResults
              export PATH="$PATH:/root/.dotnet/tools"
              dotnet tool install -g trx2junit
              trx2junit Tests/**/TestResults/*.trx --output Tests/TestResults
      # Store test result so can view in the Test tab
      - store_test_results:
          path: Tests/TestResults
      # Export test result as artifacts
      - store_artifacts:
          path: Tests/TestResults
          destination: TestResults
  build-backend-deployment-package:
    description: Build backend deployment package
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout 
      - run:
          name: "Build Backend Application with Release configuration"
          command: dotnet build --configuration Release
  run-frontend-unit-tests:
    description: Setup and run frontend unit tests
    docker:
      - image: cimg/node:14.10.1
    steps:
      # Checkout the code.
      - checkout
      # Run all unit tests in the solution
      - run:
          name: Run all unit tests in the backend application
          command: echo "Run frontend unit test - for POC only"
  build-frontend-deployment-package:
    description: Build frontend deployment package
    docker:
      - image: cimg/node:14.10.1
    steps:
      # Checkout the code.
      - checkout
      # Run all unit tests in the solution
      - run:
          name: Run all unit tests in the front application
          command: echo "Build frontend deployment package - for POC only"
  run-integration-tests:
    description: Run integration tests
    docker:
      - image: cimg/node:14.10.1
    steps:
      # Checkout the code.
      - checkout
      # Run all unit tests in the solution
      - run:
          name: Run all integration tests
          command: echo "Execute all integration tests - for POC only"
  deploy-backend-to-staging:
    description: Deploy backend to staging
    docker:
      - image: cimg/node:14.10.1
    steps:
      # Checkout the code.
      - checkout
      # Run all unit tests in the solution
      - run:
          name: Deploy backend to staging
          command: echo "Deploy backend to staging - for POC only"
  deploy-frontend-to-staging:
    description: Deploy frontend to staging
    docker:
      - image: cimg/node:14.10.1
    steps:
      # Checkout the code.
      - checkout
      # Run all unit tests in the solution
      - run:
          name: Deploy frontend to staging
          command: echo "Deploy frontend to staging - for POC only"
workflows:
  workflow: 
    jobs:
      - vulnerability-checker/scan
      - run-backend-unit-tests
      - run-frontend-unit-tests
      - run-integration-tests
      - build-backend-deployment-package:
          requires:
            - run-backend-unit-tests
            - run-integration-tests
      - build-frontend-deployment-package:
          requires:
            - run-frontend-unit-tests
            - run-integration-tests
      - deploy-backend-to-staging:
          requires:
            - build-backend-deployment-package
      - deploy-frontend-to-staging:
          requires:
            - build-frontend-deployment-package
